name: Enchant
version: '1.0'
main: org.ToothBrush.enchant.Enchant
api-version: '1.20'
libraries:
  - io.github.monun:invfx-core:3.3.2
  - io.github.monun:tap-core:4.9.8
  - io.github.monun:kommand-core:3.1.7
